Feat/rhythm list
Yugayoung/dailyrhythm pull request #7
Opened 2024-06-28 10:00 UTC by Yugayoung

마지막 커밋은 무시해주세요!

2024-07-01 11:33 UTC, Songchangyeop commented on src/components/ui/ButtonComponent.tsx
> +  text?: string | React.ReactNode;
string을 ReactNode로 쓸 수 있어요 
ReactNode로 string까지 커버 할 수 있어요

2024-07-01 11:35 UTC, Songchangyeop commented on src/components/ui/ButtonComponent.tsx
> +  width = 'auto',
버튼을 사용하는곳에 따라 다른 스타일의 버튼을 보여줘야 한다면 
width라는 props 대신에 className을 Props로 받아 사용하는 곳에서 className으로 스타일링을 하면 좋아요

2024-07-01 11:49 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +    useState<string>('');
기본값이 있다면 타입 추론이 되기 때문에 제네릭으로 타입을 지정해주지 않아도 돼요

2024-07-01 11:50 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +  onClick: () => void;
좀 더 명시적인 이름이 어떨까요?

2024-07-01 11:51 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +  const iconOptions = ['✅', '💊', '💪', '📖', '🔥'];
상수는 컴포넌트 밖에 대문자 스네이크 표기법으로 선언하는게 좋을 것 같아요

2024-07-01 11:51 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +  const format = 'HH:mm';
상수 분리해주세용

2024-07-01 11:54 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +  }
input에 글자가 입력 될때마다 setState를 호출하면 불필요한 리렌더링이 너무 많이 일어날텐데 디바운스를 사용하는건 어떨까요??

https://velog.io/@jiynn_12/Debounce-%EC%99%80-throttle-%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B3%A0-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-%EC%A0%81%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90

2024-07-01 11:56 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +  });
리액트 쿼리를 이용한 api 호출 등 로직은 hook으로 분리하는 걸 추천드려요

2024-07-01 12:02 UTC, Songchangyeop commented on src/components/AddRhythm.tsx
> +          <StyledIconOptionBox $isVisible={isVisible}>
특정 상태를 이용한 조건부 렌더링의 경우 isVisible && <...> 방식으로 처리해주세요 
visibisily와 같은 조건부 스타일링의 경우 컴포넌트는 렌더링 되지만 보이지만 않는 것이기 때문에 불 필요한 렌더링이 일어 날거에요

2024-07-01 12:14 UTC, Songchangyeop commented on src/components/RhythmList.tsx
> +    <section id='RhythmList'>
id는 어디서 쓰이나요?

2024-07-01 12:19 UTC, Songchangyeop commented on src/components/RhythmList.tsx
> +        </StyledModalOverlay>
모달 컴포넌트도 공용으로 쓸 수 있게 분리 해보면 어떨까요?

2024-07-01 12:22 UTC, Songchangyeop commented on src/components/Navbar.tsx
> +          )}
이건 어떨까요?

```jsx
const currentLogo = isDarkMode ? basicLogoDark : basicLogoLight;

<LogoImg src={currnetLogo}>
```

2024-07-01 12:33 UTC, Songchangyeop requested changes

2024-07-01 12:33 UTC, Songchangyeop commented on src/components/ProtectedRoute.tsx
> +}
좋네요 👍

2024-07-05 21:35 UTC, Yugayoung commented on src/components/ui/ButtonComponent.tsx
> +  width = 'auto',
질문 후 수정하겠습니다!

2024-07-05 21:35 UTC, Yugayoung commented on src/components/AddRhythm.tsx
> +  }
질문 후 수정하겠습니다!

2024-07-05 21:37 UTC, merged